config/routes.rb
Rails.application.routes.draw do
  
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  resources :bookings
  get "document/:id" => "bookings#document", as: :document
  resources :inquiries do
    get :edit_inquiry
    post :update_inquiry
  end
  get "approved/:id/:status" => "inquiries#approved"
  resources :static_pages do
    collection do
      get :about_us 
      get :how_it_works 
      get :testimonials 
      get :blog 
      get "leave_comment/:id" => "static_pages#leave_comment", as: :leave_comment
      post "comments/:id" => "static_pages#comments", as: :comments
    end 
  end

  resources :blogs do
    resources :comments
  end
  
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :reviews
  get 'home/index'

  resources :listings
  devise_for :contacts, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords", confirmations: "confirmations" }
  get 'dashboard/index'

  resources :contacts 

  get "confirmation/:token" => "contacts#confirmation", as: :confirmation
  get "register" => "contacts#register", as: :register
  get "payment_section" => "contacts#payment_section", as: :payment_section
  post "save_contact" => "contacts#save_contact"
  post "webhook_events" => "contacts#webhook_events"
  get "paypal_checkout" => "contacts#paypal_checkout"
  get "confirm" => "contacts#confirm"
  get "states/:country_id" => "contacts#states"
  get "cities/:state_id" => "contacts#cities"
  get "sub_category/:cat_id" => "contacts#sub_category"
  get "edit_states/:country_id/:state_id" => "contacts#edit_states"
  get "edit_sub_category/:cat_id/:sub_category" => "contacts#edit_sub_category"
  
  resources :dashboards do
    get :get_events, on: :collection, format: :json
    get 'portal', on: :collection
  end

  resources :home do 
    get :search , on: :collection
    member do
      get :sub_categories 
    end
  end
  
  root 'home#index'

  resources :artist_profiles do
    get :top_artist_profiles , on: :collection
    member do
      get :download
      get :artist_profile_details 
    end
    resources :profile_videos
    resources :profile_images
  end
  
  resources :artist_service_orders 

  resources :calenders

  resources :billings

  resources :availabilities

  resources :categories do
    member do
      get :category_artist_profiles 
      get :artist_profile_inquiry
    end
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  

  namespace :admin do
    get "/" => "contacts#new"
    get "sign_out" => "contacts#sign_out"
    resources :listings
    resources :contacts do 
      get :new_contact , on: :collection
      post :save_contact, on: :collection
    end
    resources :categories
    resources :artist_profiles do
      get :artist_profile_details
    end
    resources :dashboards
    resources :testimonials
    resources :abouts
    resources :how_it_works
    resources :blogs
    resources :inquiries
    resources :banners
    resources :social_media_links
    resources :users 
    post "about_update/:id" => "abouts#about_update", as: :about_update
   
    get 'update_profile/:id/:status' => "dashboards#update_profile"
  end
end

app/models/artist_service_order.rb
class ArtistServiceOrder < ActiveRecord::Base

	belongs_to :artist_profile
	has_many :inquiry_profiles
  validates_presence_of :service_start, :service_end, :so_summary, :new_artist_fee_cents, presence: true , on: :create

	def as_json(options = {})
    {
      :id => self.id,
      :title => self.so_summary,
      :start => self.service_start,
      :end => self.service_end,
     }
  end
end

app/controllers/artist_service_orders_controller.rb
class ArtistServiceOrdersController < ApplicationController
	before_action :authenticate_contact!
	def index
		@artist_service_orders = ArtistServiceOrder.where("artist_profile_id IN (?)",current_contact.artist_profiles.pluck(:id))

		respond_to do |format|
	    format.html # index.html.erb
	    format.json { render :json => @artist_service_orders }
	  end
		
	end

	def new
		@artist_service_order = ArtistServiceOrder.new
		respond_to do |format|
	    format.html # index.html.erb
	    #format.js
	  end
	end

	def edit
		@artist_service_order = ArtistServiceOrder.find(params[:id])
	end

	def create
		@artist_service_order = ArtistServiceOrder.new(artist_service_order_params)

    respond_to do |format|
      if @artist_service_order.save
        format.html { redirect_to artist_service_orders_url, notice: 'Service order was successfully created.' }
        format.json { render :show, status: :created, location: @@artist_service_order }
      else
        format.html { render :new }
        format.json { render json: @artist_service_order.errors, status: :unprocessable_entity }
      end
   	end
  end

  def update
   	@artist_service_order = ArtistServiceOrder.find(params[:id])
    
    respond_to do |format|
      if @artist_service_order.update_attributes(artist_service_order_params)
        format.html { redirect_to artist_service_orders_url, notice: 'Service order was successfully created.' }
        format.json { render :show, status: :created, location: @@artist_service_order }
      else
        format.html { render :new }
        format.json { render json: @artist_service_order.errors, status: :unprocessable_entity }
      end
   	end
	end

	private

	def artist_service_order_params
		params.require(:artist_service_order).permit!
	end
end

app/helpers/artist_service_orders_helper.rb
module ArtistServiceOrdersHelper
end

app/views/artist_service_orders/_form.html.erb
<div class="inner-page clearfix">
  <div class="container">
    <%= form_for(@artist_service_order) do |f| %>
      <div class="inner-ttl">Service Order </div>
      <div class="form-block">
        <div class="form-padding so-section">
          <div class="row">
          <div class="col-md-6">
            <div class="text-field">
              <%= f.label :artist_profile_id %>
              <%= f.select :artist_profile_id, options_for_select(current_contact.artist_profiles.map{|s|[s.title, s.id]}, f.object.artist_profile_id),{include_blank: "Select Profile"}, class: "form-control" %>
            </div>
          </div>
          </div>
          
            <%= render partial: "artist_service_orders/service_orders_section", locals: {sof: f, po_index:1, gross_commission:20} %>
          

        </div>

        <div class="cust_detail_btn">
          <div class="text-center">
            <%= f.submit "Save & Close", class: "send-btn"%>&nbsp;
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

</br>

<script type="text/javascript">       
  $(function () {
    $('.datepick').each(function(){
      $(this).datetimepicker({
        sideBySide: true
      });
    });
  });
</script>

app/views/artist_service_orders/_service_order.html.erb
<%= form_for(@artist_service_order) do |f| %>
  
  
  <%= f.label :artist_profile_id %>
  <%= f.select :artist_profile_id, options_for_select(ArtistProfile.all.map{|s|[s.p_name, s.id]}) %>

  <div class="panel panel-default">    
      <div class="panel-heading">Service Order</div>
      <div class="panel-body so-section">
        <div class="form-group">
          <div class="row">
            <div class="col-md-4">
                <%#= f.label :service_option_id %>
                <%#= f.text_field :service_option_id %>             
                <%= f.label "Service Order Summary "%>
            </div>
            <div class="col-md-8">
             <%= f.text_field :so_summary, class:  "form-control" %> 
            </div>
          </div>  
          <div class="row">
            <div class="col-md-4">
              <%= f.label "Further Details" %>
            </div>
            <div class="col-md-8">     
               <%= f.text_area :description , class:  "form-control"%> 
            </div>
          </div>          
          <div class="row">
            <div class="col-md-4">
              <%= f.label "Appointment Start" %>
            </div>
            <div class="col-md-8">  
                <%= f.hidden_field :service_start %>   
                <%#= render partial: "shared/datetime_picker", locals: {:form => f, :date_item=> :service_start, :extra_class => "start-datetime"} %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <%= f.label "Appointment End" %>
            </div>
            <div class="col-md-8">
                <%= f.hidden_field :service_end %>     
                <%#= render partial: "shared/datetime_picker", locals: {:form => f, :date_item=> :service_end, :extra_class => "end-datetime"} %>
            </div>
          </div>  
          <div class="row">
            <div class="col-md-2">
              <%= f.label "Perf Duration" %>
            </div>
            <div class="col-md-4">     
              <%= f.text_field :total_performance_duration,  class:  "form-control perf_duration" %>
            </div>
            <div class="col-md-3">
              <%= f.label "Callout Duration" %>
            </div>
            <div class="col-md-3">     
              <%= f.text_field :callout_duration,  class:  "form-control"%>
            </div>
          </div>
           
          <br>
         
          <%#= render partial: "service_orders/service_orders_payment_grid_gross", locals: {sof: sof, po_index:po_index, po_gross_comm:gross_commission, lastid: mainid} %>
          
        </div>
      </div>
    </div>
  
     

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">       
  $(function () {
    $('.datepick').each(function(){
      $(this).datetimepicker({
        sideBySide: true
      });
    });
  });
</script>

app/views/artist_service_orders/_service_orders_section.html.erb
<div class="row ">
  <div class="col-md-6">
    <div class="text-field">
      <%= sof.label "Service Order Summary "%>
      <%= sof.text_field :so_summary, class:  "form-control" %> 
    </div>
    <div class="text-field">
      <%= sof.label "Further Details" %>
      <%= sof.text_area :description , class:  "form-control"%> 
    </div>          
    <div class="text-field">
      <%= sof.label "Appointment Start" %>
      <%= sof.text_field :service_start , class:  "form-control start-datetime datepicker"%> 
    </div>
    <div class="text-field">
      <%= sof.label "Appointment End" %>
      <%= sof.text_field :service_end , class:  "form-control end-datetime datepicker"%> 
    </div>  
    <div class="text-field">
      <%= sof.label "Perf Duration" %>
      <%= sof.text_field :total_performance_duration,  class:  "form-control perf_duration" %>
    </div>
    <div class="text-field">
      <%= sof.label "Artist Fee" %>
      <%= sof.text_field :new_artist_fee_cents,  class:  "form-control" %>
    </div>
  </div>

  <div class="col-md-6 chk-box-list">
    <div class="row mb10 text-center">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        Reminder Required
      </div>
      <div class="col-md-4">
        Confirmation
      </div>
    </div>       
    <div class="row">
      <div class="col-md-4">
        <%= sof.label 'Travel' %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :travel_req %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :travel_conf %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= sof.label 'Accommodation' %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :accommodation_req %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :accommodation_conf %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= sof.label 'Ground Transfers' %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :ground_transfers_req %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :ground_transfers_conf %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= sof.label 'Meals' %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :meals_req %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :meals_conf %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-4">
        <%= sof.label 'Artist Equipment' %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :artist_equipment_req %>
      </div>
      <div class="col-md-4">
        <%= sof.check_box :artist_equipment_conf %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

$(function() {
  $('.datepicker').datetimepicker({
      format: "YYYY-MM-DD LT",
      sideBySide: true
    });
  addProfileOrderCallbacks(); 

  
      
});
</script>



      
      

app/views/artist_service_orders/edit.html.erb
<h1>Editing Service Order</h1>

<%= render 'form' %>

app/views/artist_service_orders/index.html.erb
<div class="container">   
  <div class="row">
    <div class="col-md-8">
      <h1>Appointments (Service Orders)</h1>
    </div>
    <div class="col-md-4 text-right">
      <h1><%= link_to 'New Service Order', new_artist_service_order_path, :class => "btn btn-default align-center"  %></h1>
    </div>
  </div>
  <% if @artist_service_orders.present? %>
    <div class="table-responsive table-first">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Profile Title</th>
            <th>Start Date</th>
            <th>Start Time</th>
            <th>Performance duration</th>
            <th>Summary</th>
            <th>Artist Fee</th>
            
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @artist_service_orders.each do |service_order| %>
            <tr>
              <td><%= service_order.artist_profile.title %></td>
              <td><%= service_order.service_start.strftime("%A, %d %b %Y %l:%M %p") %></td>
              <td><%= service_order.service_end.strftime("%A, %d %b %Y %l:%M %p") %></td>
              <td><%= service_order.total_performance_duration %></td>
              <td><%= service_order.so_summary %></td>
              <td>$<%= number_with_precision(service_order.new_artist_fee_cents, precision: 2)  %></td>
              <td><%= link_to '', edit_artist_service_order_path(service_order), class: "fa fa-pencil-square-o btn-edit" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="pull-right">
      <%#= will_paginate @artist_service_orders, renderer: BootstrapPagination::Rails %>
    </div>

  <% else %>
     <p>Record Not Found</p>
  <% end %>
</div>
<br>

app/views/artist_service_orders/new.html.erb
<%= render 'form' %>

app/views/artist_service_orders/new.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Terms And Condition");
 
// Render the edit form
$('.modal-body').html('<%= j render("service_order") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/artist_service_orders/show.html.erb
<%= render 'shared/orders_nav_bar' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Service option:</strong>
  <%= @service_order.service_option %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service_order.description %>
</p>

<p>
  <strong>Service start:</strong>
  <%= @service_order.service_start %>
</p>

<p>
  <strong>Service duration:</strong>
  <%= @service_order.service_duration %>
</p>

<p>
  <strong>So title:</strong>
  <%= @service_order.so_title %>
</p>

<p>
  <strong>So description:</strong>
  <%= @service_order.so_description %>
</p>

<p>
  <strong>So price:</strong>
  <%= @service_order.so_price %>
</p>

<%= link_to 'Edit', edit_service_order_path(@service_order) %> |
<%= link_to 'Back', service_orders_path %>