config/routes.rb
Rails.application.routes.draw do
  
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  resources :bookings
  get "document/:id" => "bookings#document", as: :document
  resources :inquiries do
    get :edit_inquiry
    post :update_inquiry
  end
  get "approved/:id/:status" => "inquiries#approved"
  resources :static_pages do
    collection do
      get :about_us 
      get :how_it_works 
      get :testimonials 
      get :blog 
      get "leave_comment/:id" => "static_pages#leave_comment", as: :leave_comment
      post "comments/:id" => "static_pages#comments", as: :comments
    end 
  end

  resources :blogs do
    resources :comments
  end
  
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :reviews
  get 'home/index'

  resources :listings
  devise_for :contacts, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords", confirmations: "confirmations" }
  get 'dashboard/index'

  resources :contacts 

  get "confirmation/:token" => "contacts#confirmation", as: :confirmation
  get "register" => "contacts#register", as: :register
  get "payment_section" => "contacts#payment_section", as: :payment_section
  post "save_contact" => "contacts#save_contact"
  post "webhook_events" => "contacts#webhook_events"
  get "paypal_checkout" => "contacts#paypal_checkout"
  get "confirm" => "contacts#confirm"
  get "states/:country_id" => "contacts#states"
  get "cities/:state_id" => "contacts#cities"
  get "sub_category/:cat_id" => "contacts#sub_category"
  get "edit_states/:country_id/:state_id" => "contacts#edit_states"
  get "edit_sub_category/:cat_id/:sub_category" => "contacts#edit_sub_category"
  
  resources :dashboards do
    get :get_events, on: :collection, format: :json
    get 'portal', on: :collection
  end

  resources :home do 
    get :search , on: :collection
    member do
      get :sub_categories 
    end
  end
  
  root 'home#index'

  resources :artist_profiles do
    get :top_artist_profiles , on: :collection
    member do
      get :download
      get :artist_profile_details 
    end
    resources :profile_videos
    resources :profile_images
  end
  
  resources :artist_service_orders 

  resources :calenders

  resources :billings

  resources :availabilities

  resources :categories do
    member do
      get :category_artist_profiles 
      get :artist_profile_inquiry
    end
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  

  namespace :admin do
    get "/" => "contacts#new"
    get "sign_out" => "contacts#sign_out"
    resources :listings
    resources :contacts do 
      get :new_contact , on: :collection
      post :save_contact, on: :collection
    end
    resources :categories
    resources :artist_profiles do
      get :artist_profile_details
    end
    resources :dashboards
    resources :testimonials
    resources :abouts
    resources :how_it_works
    resources :blogs
    resources :inquiries
    resources :banners
    resources :social_media_links
    resources :users 
    post "about_update/:id" => "abouts#about_update", as: :about_update
   
    get 'update_profile/:id/:status' => "dashboards#update_profile"
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :contact

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_attached_file :audio, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :audio, :content_type => ['audio/mpeg']

end

app/controllers/admin/listings_controller.rb
class Admin::ListingsController < ApplicationController
	before_action :authenticate_contact!
	layout "admin"
	
	def index
		@listings = Listing.all.paginate(:page => params[:page], :per_page => 7)
	end
	def new
		@listing = Listing.new
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_contact!
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    @package = "Listings"
    @listings = Listing.paginate(:page => params[:page], :per_page => 7)
  end

  def show
  end

  def new
    @listing = Listing.new
   # @contact.listings.build
  end

  def edit
  end

  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:objectTitle, :objectLocation1, :objectLocation2, :objectCountry, :objectPrimaryCategoryID, :objectRootCategoryId, :objectDescription1, :objectDescription2, :objectKeywords, :objectPricing, :objectEnabled, :dateLevelExpires, :objectTypeID, :objectStatus, :objectApproved, :objectApproved, :cotact_id)
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>

  <%= f.error_notification %>
  
  <div class="form-inputs step2">
    <div class="col-md-8">
      <%= f.input :objectTitle, label: "*Title" %>
      <%= f.input :objectLocation1, label: "*SUBURB/TOWN" %>
      <%= f.input :objectLocation2, label: "*CITY" %>
      <%= f.input :objectCountry, label: "*COUNTRY" %>
      <%= f.input :objectPrimaryCategoryID, label: "*PRIMARY CATEGORY" %>
      <%= f.input :objectRootCategoryId, label: "" %>
      <%= f.input :objectDescription1, label: "*SHORT DESCRIPTION" %>
      <%= f.input :objectDescription2, label: "*LONG DESCRIPTION" %>
      <%= f.input :objectKeywords, label: "*KEYWORDS" %>
      <%= f.input :objectPricing, label: "*PRICING" %>
      
      
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    </div>
  </div>

<% end %>

</br>

<script type="text/javascript">
$(".steps").click(function () {
  if($('#contact_contact_type_2').is(':checked')){
    $('.step1').hide();
    $('.step3').show();
  }else{
    $('.step3').hide();
    $('.step1').hide();
    $('.step2').show();
  }
});

</script>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>


<%= simple_form_for(@listing) do |f| %>

  <%= f.error_notification %>
  <div class="form-inputs step2">
    <div class="col-md-8">
      <%= f.input :objectTitle, label: "*Title" %>
      <%= f.input :objectLocation1, label: "*SUBURB/TOWN" %>
      <%= f.input :objectLocation2, label: "*CITY" %>
      <%= f.input :objectCountry, label: "*COUNTRY" %>
      <%= f.input :objectPrimaryCategoryID, label: "*PRIMARY CATEGORY" %>
      <%= f.input :objectRootCategoryId, label: "" %>
      <%= f.input :objectDescription1, label: "*SHORT DESCRIPTION" %>
      <%= f.input :objectDescription2, label: "*LONG DESCRIPTION" %>
      <%= f.input :objectKeywords, label: "*KEYWORDS" %>
      <%= f.input :objectPricing, label: "*PRICING" %>
      
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    </div>
  </div>

<% end %>

</br>

<script type="text/javascript">
$(".steps").click(function () {
  $('.step1').hide();
  $('.step2').show();
});

</script>

app/views/listings/index.html.erb
<h1>Listings</h1>

<div class="row">
  <div class="col-md-12 text-right">
    <h1><%= link_to 'New Listing', new_listing_path, :class => "btn btn-default align-center"  %></h1>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Ttitle</th>
      <th>Location</th>
      <th>State</th>
      <th>Status</th>
      <th>Level</th>
      <th>Enabled</th>
      <th>Approved</th>
      <th>Joined</th>
      <th>Modified</th>
      <td colspan="2">Actions</td>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.objectTitle %></td>
        <td><%= listing.objectLocation1 %></td>
        <td><%= listing.objectLocation2 %></td>
        <td><%= listing.objectStatus %></td>
        <td><%= listing.objectDescription1 %></td>
        <td><%= listing.objectEnabled ? "TRUE" : "FALSE" %></td>
        <td><%= listing.objectApproved ? "TRUE" : "FALSE" %></td>
        <td><%= listing.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= listing.updated_at.strftime('%d/%m/%Y') %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pull-right">
  <%= will_paginate @listings, renderer: BootstrapPagination::Rails %>
</div>

<br>

app/views/listings/new.html.erb
<%= render 'form' %>
</br>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Objecttitle:</strong>
  <%= @listing.objectTitle %>
</p>

<p>
  <strong>Objectlocation1:</strong>
  <%= @listing.objectLocation1 %>
</p>

<p>
  <strong>Objectlocation2:</strong>
  <%= @listing.objectLocation2 %>
</p>

<p>
  <strong>Objectcountry:</strong>
  <%= @listing.objectCountry %>
</p>

<p>
  <strong>Objectprimarycategoryid:</strong>
  <%= @listing.objectPrimaryCategoryID %>
</p>

<p>
  <strong>Objectrootcategoryid:</strong>
  <%= @listing.objectRootCategoryId %>
</p>

<p>
  <strong>Objectdescription1:</strong>
  <%= @listing.objectDescription1 %>
</p>

<p>
  <strong>Objectdescription2:</strong>
  <%= @listing.objectDescription2 %>
</p>

<p>
  <strong>Objectkeywords:</strong>
  <%= @listing.objectKeywords %>
</p>

<p>
  <strong>Objectpricing:</strong>
  <%= @listing.objectPricing %>
</p>

<p>
  <strong>Objectenabled:</strong>
  <%= @listing.objectEnabled %>
</p>

<p>
  <strong>Datelevelexpires:</strong>
  <%= @listing.dateLevelExpires %>
</p>

<p>
  <strong>Objecttypeid:</strong>
  <%= @listing.objectTypeID %>
</p>

<p>
  <strong>Objectstatus:</strong>
  <%= @listing.objectStatus %>
</p>

<p>
  <strong>Objectapproved:</strong>
  <%= @listing.objectApproved %>
</p>

<p>
  <strong>Objectapproved:</strong>
  <%= @listing.objectApproved %>
</p>

<p>
  <strong>Cotact:</strong>
  <%= @listing.cotact_id %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>