config/routes.rb
Rails.application.routes.draw do
  
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  resources :bookings
  get "document/:id" => "bookings#document", as: :document
  resources :inquiries do
    get :edit_inquiry
    post :update_inquiry
  end
  get "approved/:id/:status" => "inquiries#approved"
  resources :static_pages do
    collection do
      get :about_us 
      get :how_it_works 
      get :testimonials 
      get :blog 
      get "leave_comment/:id" => "static_pages#leave_comment", as: :leave_comment
      post "comments/:id" => "static_pages#comments", as: :comments
    end 
  end

  resources :blogs do
    resources :comments
  end
  
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :reviews
  get 'home/index'

  resources :listings
  devise_for :contacts, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords", confirmations: "confirmations" }
  get 'dashboard/index'

  resources :contacts 

  get "confirmation/:token" => "contacts#confirmation", as: :confirmation
  get "register" => "contacts#register", as: :register
  get "payment_section" => "contacts#payment_section", as: :payment_section
  post "save_contact" => "contacts#save_contact"
  post "webhook_events" => "contacts#webhook_events"
  get "paypal_checkout" => "contacts#paypal_checkout"
  get "confirm" => "contacts#confirm"
  get "states/:country_id" => "contacts#states"
  get "cities/:state_id" => "contacts#cities"
  get "sub_category/:cat_id" => "contacts#sub_category"
  get "edit_states/:country_id/:state_id" => "contacts#edit_states"
  get "edit_sub_category/:cat_id/:sub_category" => "contacts#edit_sub_category"
  
  resources :dashboards do
    get :get_events, on: :collection, format: :json
    get 'portal', on: :collection
  end

  resources :home do 
    get :search , on: :collection
    member do
      get :sub_categories 
    end
  end
  
  root 'home#index'

  resources :artist_profiles do
    get :top_artist_profiles , on: :collection
    member do
      get :download
      get :artist_profile_details 
    end
    resources :profile_videos
    resources :profile_images
  end
  
  resources :artist_service_orders 

  resources :calenders

  resources :billings

  resources :availabilities

  resources :categories do
    member do
      get :category_artist_profiles 
      get :artist_profile_inquiry
    end
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  

  namespace :admin do
    get "/" => "contacts#new"
    get "sign_out" => "contacts#sign_out"
    resources :listings
    resources :contacts do 
      get :new_contact , on: :collection
      post :save_contact, on: :collection
    end
    resources :categories
    resources :artist_profiles do
      get :artist_profile_details
    end
    resources :dashboards
    resources :testimonials
    resources :abouts
    resources :how_it_works
    resources :blogs
    resources :inquiries
    resources :banners
    resources :social_media_links
    resources :users 
    post "about_update/:id" => "abouts#about_update", as: :about_update
   
    get 'update_profile/:id/:status' => "dashboards#update_profile"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'date'
  require 'time'
 
  def index
    @package = "Australias Premier Entertainment Agency"
    @categories= Category.where("ancestry is null")
    @artist_profiles = ArtistProfile.where(approved: true).all.limit(6)
    @sub_categories = Category.where("ancestry != ?", "")
    @popular_categories1 = Category.where("ancestry != ?", "").order("RANDOM()").limit(6)
    @popular_categories = Category.where("ancestry != ?", "").order("RANDOM()")
    @popular_category = []
    @popular_categories.each do |category|
      @popular_category << category
    end
    @featured_artist = ArtistProfile.where(approved: true).order("RANDOM()").limit(8)
  end

  def search
    if params[:search].present? and params[:location2].present?
       @artist_profiles = ArtistProfile.approved.search_by_artist_title_keyword_body(params[:search],params[:sub_category_id], params[:location2])

    elsif params[:search].present? and params[:country].present?
      abort
      @artist_profiles = ArtistProfile.approved.search_by_artist_title_keyword_body(params[:search], params[:sub_category_id], params[:location2]).where("country NOT IN (?) and location2 NOT IN (?)", "AU", Category::CITYES)

    elsif params[:search].present? 
      @artist_profiles = ArtistProfile.approved.search_by_artist_title_keyword_body(params[:search], params[:sub_category_id], params[:location2])

    elsif params[:location].present?
       @artist_profiles = ArtistProfile.where("location2 =? and sub_category_id =? and approved =? ", params[:location], params[:id], true)
    elsif params[:country].present?

      where = ""
      where += "keywords = '#{params[:keywords]}'" if !params[:keywords].blank?
      cond = (!where.blank?) ? " AND " : ""
      where += " #{cond} category_id = '#{params[:category_id]}'" if !params[:category_id].blank?
      cond = (!where.blank?) ? " AND " : ""
      where += " #{cond} sub_category_id = '#{params[:sub_category_id]}' " if !params[:sub_category_id].blank?
      cond = (!where.blank?) ? " AND " : ""
      where += " #{cond} price = '#{params[:price]}'" if !params[:price].blank?
      cond = (!where.blank?) ? " AND " : ""
      if where.present?
        @artist_profiles = ArtistProfile.approved.where("country NOT IN (?) or location2 NOT IN (?)", "AU", Category::CITYES).where(where)
      elsif params[:date].present?
        @artist_profiles = ArtistProfile.approved.where(where).joins(:availables).uniq.search(params[:date]).where("country NOT IN (?) or location2 NOT IN (?)", "AU", Category::CITYES)
      else
        @artist_profiles = ArtistProfile.approved.where("country NOT IN (?) and location2 NOT IN (?)", "AU", Category::CITYES)
      end
    else 
      @categories_header = Category.where("ancestry is null")
      where = ""
        where += " #{cond} category_id = '#{params[:category_id]}'" if !params[:category_id].blank?
        cond = (!where.blank?) ? " AND " : ""
        where += " #{cond} sub_category_id = '#{params[:sub_category_id]}' " if !params[:sub_category_id].blank?
        cond = (!where.blank?) ? " AND " : ""
        where += " #{cond} location2 = '#{params[:location2]}'" if !params[:location2].blank?
        cond = (!where.blank?) ? " AND " : ""
        where += " #{cond} price = '#{params[:price]}'" if !params[:price].blank?
        cond = (!where.blank?) ? " AND " : ""
        where += " #{cond} category_id = '#{params[:category]}'" if !params[:category].blank?
        if where.present?
          if params[:date].present?
            @artist_profiles = ArtistProfile.approved.where(where).joins(:availables).uniq.search(params[:date])
          elsif params[:keywords].present?
            @artist_profiles = ArtistProfile.approved.where(where).search_by_artist_title_and_keyword_and_body(params[:keywords])
          else
            @artist_profiles = ArtistProfile.approved.where(where)
          end
        elsif params[:date].present?
          @artist_profiles = ArtistProfile.approved.joins(:contact).joins(:availables).uniq.search(params[:date])
        elsif params[:keywords].present?
          @artist_profiles = ArtistProfile.approved.search_by_artist_title_and_keyword_and_body(params[:keywords])
        else 
          @artist_profiles = ArtistProfile.approved
        end
      end
  end


  def sub_categories
  @sub_categories = Category.where("ancestry = ?", params[:id])
    @sub_categories = @sub_categories.select('id, name').map do |cat|
      [cat.name, cat.id]
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- SEARCH SECTION -->
<div class="search_sect bg_pink">
  <div class="search_container container ">
    <div class="fetured-title pink bold">
      <div class="text-uppercase white"> What are you looking for? </div>
    </div>

    <%= form_tag search_home_index_path, :method => 'get', id: "register_form" do %>
      <div class="col-md-12 no-padding home_search">
        <div class="col-md-2 col-sm-2 search-text">
          <%= select_tag :category_id, options_from_collection_for_select(@categories, :id, :name), :prompt => "Select Category" , class: "form-control" %>
        </div>

        <div class="col-md-2 col-sm-2 search-text">
          <%= select_tag :sub_category_id,"", :prompt => "Select Sub Category" , class: "form-control", id: "sub_categories" %>
        </div>

        <div class="col-md-2 col-sm-2 search-text key">
          <%= text_field_tag :keywords, '', class: "form-control", placeholder: "Keywords:"%>
        </div>

        <div class="col-md-2 col-sm-2 search-text">
          <%= select_tag :location2, options_for_select(Category::CITYES), :prompt => "Select Location", class: "form-control" %>
        </div>
        <div class="col-md-2 col-sm-2 search-text dt">
          <input type="text" class="form-control" name="date" id="datepick" placeholder="Date & Time:" />
        </div>
        <div class="col-md-2 col-sm-2 search-text">
          <%= select_tag :price, options_for_select(ArtistProfile::PRICING), :prompt => "Select Budget", class: "form-control" %>
        </div>
        <div class="col-md-2 col-sm-2 search-text key">
          <%= submit_tag "Search", :name => nil, class: "btn-search products_search" %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<!--MOST POPULAR SECTION-->
<div class="popular_sect clearfix">
  <div class="fetured-title pink bold">
    <div class="text-uppercase white"> most popular categories & new listings </div>
  </div>
  
  <div class="clearfix">
    <div class="col-md-2 col-sm-4 popular-block "> <a href="#">
      <div class="popular-img popular_odd"> 
        <% if @popular_category[0].present? %>
          <%= link_to category_artist_profiles_category_path(@popular_category[0].id) do %> <%= image_tag @popular_category[0].image.url%> 
          <div class="popular-text"><%= @popular_category[0].name %></div><% end %>
        <% end %>
      </div>
      </a> </div>
    <div class="col-md-4 col-sm-8 popular-block"> <a href="#">
      <div class="popular-img  popular_even"> 
        <% if @popular_category[1].present? %>
          <%= link_to category_artist_profiles_category_path(@popular_category[1].id) do %> <%= image_tag @popular_category[1].image.url%> 
          <div class="popular-text"><%= @popular_category[1].name %></div><% end %>
        <% end %>
      </div>
      </a> </div>
    <div class="col-md-4 col-sm-8 popular-block"> <a href="#">
      <div class="popular-img popular_even"> 
        <% if @popular_category[2].present? %>
          <%= link_to category_artist_profiles_category_path(@popular_category[2].id) do %> <%= image_tag @popular_category[2].image.url%> 
          <div class="popular-text"><%= @popular_category[2].name %></div><% end %>
        <% end %>
      </div>
      </a> </div>
    <div class="col-md-2 col-sm-4 popular-block"> <a href="#">
      <div class="popular-img popular_odd">
        <% if @popular_category[3].present? %>
          <%= link_to category_artist_profiles_category_path(@popular_category[3].id) do %>  <%= image_tag @popular_category[3].image.url%> 
          <div class="popular-text"><%= @popular_category[3].name %></div><% end %>
        <% end %>
      </div>
      </a> </div>
  </div>
  <div class="clearfix">
    <% @popular_categories1.each do |cat|%>
      <div class="col-md-2 col-sm-4 popular-block"> 
        <a href="#">
          <div class="popular-img popular-bottom"> <%= link_to category_artist_profiles_category_path(cat.id) do %><%= image_tag cat.image.url %> 
            <div class="popular-text"><%= cat.name %></div><% end %>
          </div>
        </a>
      </div> 
    <% end %>
  </div>
  <div class="text-center mt40"> 
    <%= link_to "VIEW TOP 100 MOST POPULAR CATEGORIES", categories_path, class: "view-more" %>
    &nbsp;
    <%= link_to "VIEW TOP 100 NEW LISTINGS", top_artist_profiles_artist_profiles_path, class: "catogory-btn" %>
  </div>
</div>

<!-- LOOK FOR SECTION -->
<div class="look_sect bg_pink">
  <div class="container">
    <div class="big-text white"> Over thousands, entertainers and event services for hire </div>
  </div>
</div>

<!--FETIRED ARTISTS SECTION-->
<div class="fetured-artists clearfix">
  <div class="fetured-title white"> FEATURED ARTIST <span>Just some words about my career</span> </div>
  <% if @featured_artist.present? %>
    <% @count = 1 %>
    <% @featured_artist.each_slice(4) do |artist| %>
      <% artist.each do|profile| %>
        <div class="col-md-3 col-sm-3 artists-block"> 
          <div class="artists-img"> 
            <% if profile.profile_images.present? %>
              <%= link_to artist_profile_details_artist_profile_path(profile.slug) do %><%= image_tag profile.profile_images.first.image.url %> <% end %>
            <% else %>
              <%= link_to artist_profile_details_artist_profile_path(profile.slug) do %><%= "Image" %> <% end %>
            <% end %>
          </div>
          <div class="pp-text">
            <%= link_to artist_profile_details_artist_profile_path(profile.slug) do %>
              <%= profile.title %>
            <% end %>
          </div>
        </div>
        <% @count += 1 %>
      <% end %>
    <% end %>
  <% end %>
  <div class="text-center mt40"> <%= link_to "VIEW MORE CELEBRITIES", top_artist_profiles_artist_profiles_path, class: "catogory-btn" %></div>
</div>

<!--TWO COLUMN TEXT SECTION-->
<div class="bg_pink welcome_bg_sect">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 white">
        <div class="main-text">Australia's leading entertainment agency and directory</div>
        <p>&nbsp;</p>
        <p>Welcome to EntertainOz, Australia's premier entertainment booking agency, directory and speakers bureau! Catering for every budget and every occasion, we have an amazing variety of entertainers for hire including jazz, cover and tribute bands, comedians,  DJs,  speakerts,  magicians, close up magicians, celebrities, clowns, dancers,  illusionists,  opera singers,  acrobats and much,  much more!</p>

<p>Lorem ipsum is dummy text content for use in dummy text orem ipsum is dummy text content for use in dummy textorem ipsum is dummy text content for use in dummy textorem ipsum is dummy text content for use in dummy textorem ipsum is dummy text content for use in dummy textorem ipsum is dummy text content for use in dummy textorem ipsum is dummy text content.</p>
        <p>&nbsp;</p>
      </div>
      <div class="col-md-6 col-sm-6 white">
        <div class="main-text">You can book anything from corporate speakers to cover bands</div>
        <p>&nbsp;</p>
        <p>Check out our sensational selection of Australia and Melbourne cover bands and musicians for hire or laugh out loud with Australia's top male and female stand up comedians. Corporate entertainment is our speciality and our professional speakers' bureau includes only the very finest inspirational and motivational conference speakers in Adelaide, Brisbane, Melbourne and Sydney. We also have a marvellous range of wedding entertainment including wedding DJ's, compeers & MCs and party bands from Melbourne, Sydney, Adelaide, Brisbane and Perth. Book online now!</p>

<p>We make entertainment hire in Perth and across Australia easy, because we've got all of the options available in one place. With our website you can browse every type of performer you can imagine, including some you've probably never ever thought of. Once you've decided, it's straightforward to book the chosen entertainment with an uncomplicated click of a button.</p>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">       
  $(function () {
    $('#datepick').each(function(){
      $(this).datetimepicker({
        // sideBySide: true
      });
    });
  });

  $("#category_id").change(function() {
    if($(this).val() != ""){
      $.ajax({
        type: "GET",
        url:  '/home/'+ $(this).val()+'/sub_categories',
        dataType: "script"
      });
    }
  });

  $(document).ready(function () {
    $("#register_form").submit(function(e){
      if($("#category_id").val() == "" && $("#sub_categories").val() == "" && $("#keywords").val() == "" && $("#location2").val() == "" && $("#datepick").val() == "" && $("#price").val() == ""){
        alert("Select Atleast one option for search")
        return false;
      }
    });
  })
</script>

app/views/home/search.html.erb
<div class="container">
  <div class="fetured-title pink bold">
    <div class="text-uppercase Black"> <%= "Profiles" %> </div>
  </div>
  <div class="inner_search_sect bg_pink">
    <div class="col-md-7 center-block no-padding">
      <%= form_tag search_home_index_path, :method => 'get', :id => "products_search" do %>
        <%= hidden_field_tag :sub_category_id, params[:id] %>
        <div class="col-md-9 col-sm-9 search-text key">
          <%= text_field_tag :search, '', class: "form-control", placeholder: "Keywords:"%>
        </div>
        <div class="col-md-3 col-sm-3 search-text key">
          <%= submit_tag "Search", :name => nil, class: "btn-search" %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<div class="entertainers_sect clearfix">
  <div class="container">
    <div class="profile_city">
      <span><%= link_to "All", ""%> (<%= @artist_profiles.count %>)</span>
      <% Category::CITYES.each do |city| %>

        <% if params[:category_id].present? and params[:sub_category_id].present?%> 
          <span><%= link_to city, search_home_index_path(category_id:  params[:category_id], location2: city, sub_category_id: params[:sub_category_id])%> (<%= @artist_profiles.where("category_id = ? and location2 =?", params[:category_id],city).count %>)</span>

        <% elsif params[:category_id].present? and params[:price] and !params[:date].present?  %>
          <span><%= link_to city, search_home_index_path(category_id: params[:category_id],location2:  city, price: params[:price])%> (<%= @artist_profiles.where("category_id = ? and location2 =? ", params[:category_id],city).count %>)</span>

        <% elsif params[:category_id].present? and !params[:date].present?  %>
          <span><%= link_to city, search_home_index_path(category_id: params[:category_id],:location2 => city)%> (<%= @artist_profiles.where("category_id = ? and location2 =?", params[:category_id],city).count %>)</span>

        <% elsif params[:sub_category_id].present? %> 
          <span><%= link_to city, search_home_index_path(sub_category_id: params[:sub_category_id],location2: city)%> (<%= @artist_profiles.where("sub_category_id = ? and location2 =?", params[:sub_category_id],city).count %>)</span>
        
        <% elsif params[:keywords].present? %>
          <span><%= link_to city, search_home_index_path(params,location2: city,keywords: params[:keywords]) %> (<%= @artist_profiles.where("location2 =?",city).count %>)</span>
        
        <% elsif params[:location2].present? %>
          <span><%= link_to city, ""%> (<%= @artist_profiles.where("location2 = ? and location2 =?", params[:location2],city).count %>)</span>
        
        <% elsif params[:price].present? and !params[:date].present? %>
          <span><%= link_to city, search_home_index_path(params,location2: city,price:  params[:price], category_id: params[:category]) %> (<%= @artist_profiles.where("price = ? and location2 =?", params[:price],city).count %>)</span>
        
        <% elsif params[:search].present? %>
          <span><%= link_to city, search_home_index_path(params,location2: city,search: params[:search]) %> (<%= @artist_profiles.where("location2 =?", city).count %>)</span>
       
        <% elsif params[:date].present? %>
          <span><%= link_to city, search_home_index_path(params,location2: city, date: params[:date], category_id: params[:category_id], price: params[:price]) %> (<%= @artist_profiles.where("location2 =?", city).joins(:availables).where("DATE(start_at) <= ? and DATE(end_at) >= ?", params[:date],params[:date]).count %>)</span>
        <% else %>
          <span><%= link_to city, search_home_index_path(params,location2: city) %> (<%= @artist_profiles.where("location2 = ? ", city).count %>)</span>
        <% end %>
      <% end %>

      <span><%= link_to "Others", search_home_index_path(params,:country => "Other",:search => params[:search],category_id: params[:category_id], sub_category_id: params[:sub_category_id], keywords: params[:keywords], price: params[:price], date: params[:date] ) %> (<%= @artist_profiles.where("country NOT IN (?) or location2 NOT IN (?)", "AU", Category::CITYES).count %>)</span>
      
    </div>
    
    <% if @artist_profiles.present? %>
      <% @artist_profiles.each_slice(5) do |artist_profile|%>
        <div class="ent-row">
          <% artist_profile.each do|profile| %>
            <div class="col-md-3 col-sm-4 popular-block">
              <div class="artist_pro">
                <div class="artist-block">
                  <%= link_to artist_profile_details_artist_profile_path(profile.slug) do %>
                    <div class="popular-img all_categories"> 
                      <% if profile.profile_images.present? %>
                        <%= image_tag profile.profile_images.first.image.url %>
                      <% end %>
                        <div class="artist_pro_title"><%= profile.title %></br>
                        <span class="artist_pro_category"><%= Category.find(profile.sub_category_id).try(:name) %></span>
                      </div>
                    </div>
                  <% end %>
                  <div class="artist_pro_description">
                    <div class="country-type">
                      <%= profile.try(:location2) %> , <%= profile.try(:state) %> , <%= profile.try(:country) %></br>
                      <% if profile.country_wide == true %>
                        <%= "Australia-wide" %>
                      <% end %>
                    </div>
                    <div class="star-block">
                      <%= rating_for profile, "original_score", stars: 5,disable_after_rate: true, target: '#abc', targetScore: '#abc' %>
                      <div id="abc"></div>
                    </div>
                  </div> 
                  <div class="reg-block">
                    <% so_id = profile.artist_service_orders.first.id if profile.artist_service_orders.present?  %>
                    <%= link_to "Request a Quote", artist_profile_inquiry_category_path(profile.slug, service_order_id: so_id), data: {remote: true, type: "script"}, class: "btn btn-register" %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
        <%= "Artist Not Found" %>
    <% end %>
  </div>
  
</div>


<script type="text/javascript">
$(function () {
    $('#datepick').each(function(){
      $(this).datetimepicker({
        sideBySide: true
      });
    });
  });
  
</script>

app/views/home/sub_categories.js.erb
<% if @sub_categories.present?  %>
  $('#sub_categories').html("<%= escape_javascript options_for_select(@sub_categories) %>");
  $('#sub_categories').prepend($("<option></option>")
                    .attr("value","")
                    .text("Select Sub Category"));
  $('#sub_categories option[value=""]').attr('selected','selected');
<% end %>