config/routes.rb
Rails.application.routes.draw do
  
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  resources :bookings
  get "document/:id" => "bookings#document", as: :document
  resources :inquiries do
    get :edit_inquiry
    post :update_inquiry
  end
  get "approved/:id/:status" => "inquiries#approved"
  resources :static_pages do
    collection do
      get :about_us 
      get :how_it_works 
      get :testimonials 
      get :blog 
      get "leave_comment/:id" => "static_pages#leave_comment", as: :leave_comment
      post "comments/:id" => "static_pages#comments", as: :comments
    end 
  end

  resources :blogs do
    resources :comments
  end
  
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :reviews
  get 'home/index'

  resources :listings
  devise_for :contacts, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords", confirmations: "confirmations" }
  get 'dashboard/index'

  resources :contacts 

  get "confirmation/:token" => "contacts#confirmation", as: :confirmation
  get "register" => "contacts#register", as: :register
  get "payment_section" => "contacts#payment_section", as: :payment_section
  post "save_contact" => "contacts#save_contact"
  post "webhook_events" => "contacts#webhook_events"
  get "paypal_checkout" => "contacts#paypal_checkout"
  get "confirm" => "contacts#confirm"
  get "states/:country_id" => "contacts#states"
  get "cities/:state_id" => "contacts#cities"
  get "sub_category/:cat_id" => "contacts#sub_category"
  get "edit_states/:country_id/:state_id" => "contacts#edit_states"
  get "edit_sub_category/:cat_id/:sub_category" => "contacts#edit_sub_category"
  
  resources :dashboards do
    get :get_events, on: :collection, format: :json
    get 'portal', on: :collection
  end

  resources :home do 
    get :search , on: :collection
    member do
      get :sub_categories 
    end
  end
  
  root 'home#index'

  resources :artist_profiles do
    get :top_artist_profiles , on: :collection
    member do
      get :download
      get :artist_profile_details 
    end
    resources :profile_videos
    resources :profile_images
  end
  
  resources :artist_service_orders 

  resources :calenders

  resources :billings

  resources :availabilities

  resources :categories do
    member do
      get :category_artist_profiles 
      get :artist_profile_inquiry
    end
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  

  namespace :admin do
    get "/" => "contacts#new"
    get "sign_out" => "contacts#sign_out"
    resources :listings
    resources :contacts do 
      get :new_contact , on: :collection
      post :save_contact, on: :collection
    end
    resources :categories
    resources :artist_profiles do
      get :artist_profile_details
    end
    resources :dashboards
    resources :testimonials
    resources :abouts
    resources :how_it_works
    resources :blogs
    resources :inquiries
    resources :banners
    resources :social_media_links
    resources :users 
    post "about_update/:id" => "abouts#about_update", as: :about_update
   
    get 'update_profile/:id/:status' => "dashboards#update_profile"
  end
end

app/controllers/admin/abouts_controller.rb
class Admin::AboutsController < ApplicationController
  before_action :authenticate_contact!
  before_action :set_aboutus, only: [:show, :edit, :update, :destroy]

   layout "admin"

  def index
    @aboutus = AboutU.all
  end

  def new
    @aboutus = AboutU.new
  end

  def create
    @aboutus = AboutU.new(aboutus_params)

    respond_to do |format|
      if @aboutus.save
        format.html { redirect_to request.referer, notice: 'Aboutus was successfully created.' }
        format.json { render :show, status: :created, location: @aboutus }
      else
        format.html { render :new }
        format.json { render json: @aboutus.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    
  end

  def edit
    @aboutus = AboutU.find(params[:id])
  end

  def about_update
    @aboutus = AboutU.find(params[:id])
    respond_to do |format|
      if @aboutus.update(aboutus_params)
        format.html { redirect_to request.referer, notice: 'Aboutus was successfully updated.' }
        format.json { render :show, status: :ok, location: @aboutus }
      else
        format.html { render :edit }
        format.json { render json: @aboutus.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @aboutus = AboutU.find(params[:id])
    respond_to do |format|
      if @aboutus.update(aboutus_params)
        format.html { redirect_to request.referer, notice: 'Aboutus was successfully updated.' }
        format.json { render :show, status: :ok, location: @aboutus }
      else
        format.html { render :edit }
        format.json { render json: @aboutus.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @aboutus = AboutU.find(params[:id])
    @aboutus.destroy
    respond_to do |format|
      format.html { redirect_to admin_abouts_url, notice: 'Aboutus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aboutus
      @aboutus = AboutU.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aboutus_params
      params.require(:about_u).permit(:context, :about_us_image, :about_us_video)
    end
end

app/views/admin/abouts/_form.html.erb
<%= tinymce_assets %>
<%= form_for(@aboutus, url: admin_abouts_path, method: :post) do |f| %>
  <%#= f.error_notification %>

    <div class="field">
      <%= f.label :context %></br>
      <%= f.text_area :context,  :class => "tinymce", :rows => 10, :cols => 70 %>
    </div></br>

    <div class="field">
      <%= f.label :about_us_image %><br>
      <%= f.file_field :about_us_image, label: "Image" %>
    </div></br> 

    <div class="field">
      <%= f.label :about_us_video %><br>
      <%= f.file_field :about_us_video, label: "Video" %>
    </div></br>    
    

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
<%= tinymce %>

app/views/admin/abouts/edit.html.erb
<div class="container">
  <h1>Editing About Us</h1>
  <%= tinymce_assets %>
  <%= form_for(@aboutus, url: admin_about_update_path, method: :POST) do |f| %>
    <%#= f.error_notification %>

      <div class="field">
        <%= f.label :context %></br>
        <%= f.text_area :context,  :class => "tinymce", :rows => 10, :cols => 70 %>
      </div></br>

      <div class="field">
        <%= f.label :about_us_image %><br>
        <%= f.file_field :about_us_image, label: "Image" %>
      </div></br> 

      <div class="field">
        <%= f.label :about_us_video %><br>
        <%= f.file_field :about_us_video, label: "Video" %>
      </div></br>    
      

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= tinymce %>
</div>

app/views/admin/abouts/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Listing About Us</h1>
  </div>
  <div class="col-md-4 text-right">
    <h1><%= link_to "New", new_admin_about_path, class: "btn btn-primary" %></h1>
  </div>
</div>

<table id="aboutus" class="table table-striped table-hover table-responsive">
  <thead>
    <tr>
      <th>Context</th>
      <th>Image</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aboutus.each do |aboutus| %>
      <tr>
        <td class="aboutus_first"><%= raw(aboutus.context) %></td>
        <td><%= image_tag aboutus.about_us_image.url(:thumb) %></td>
        <td><%= image_tag aboutus.about_us_video.url %></td>
        <td><%= link_to 'Edit', edit_admin_about_path(aboutus) %></td>
        <td><%= link_to 'Destroy', admin_about_path(aboutus), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<style type="text/css">
/*#aboutus td {
    width: 25%;
}*/
.aboutus_first {
    width: 40% !important;
}
</style>

app/views/admin/abouts/new.html.erb
<h1>New About Us</h1>

<%= render 'form' %>